server:
  port: 8088

spring:
  application:
    name: composite
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/composite?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    #    hibernate:
    #      ddl-auto: create-drop
    generate-ddl: false
    show-sql: true
  #thymeleaf
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    servlet:
      content-type: text/html; charset=utf-8